### ISSUE TITLE
Provide a solution to chapter 01

### ISSUE THREAD

**Issue by tcd1558** [tcd1558/Python_ObjectOrientedProgramming#2]
Create your own branch with a solution for chapter 01.

**Comment by tcd1558g** [comment]
A solution for chapter 01 is provided in the tree chapter01.

**Comment by tcd1558** [comment]
instance_mine.py: swap the last 2 lines. Due to the error message, the last line is not executed. 

print(b1._Book__secret) # still accessible, but strongly discurraged.
print(b1.__secret) # creates an error message.

**Comment by tcd1558** [comment]
Merged with 2 extra changes
